### ISSUE TITLE
Any chances of a version based on 1.0.0?

### ISSUE THREAD

**Issue by jpasantos** [andifalk/custom-spring-authorization-server#1]
Hi, like the title says this isn't an issue, it's a question. I tried with no success to migrate this code to version 1.0.0 of the spring authorization server. Do you have any plans to update your code.

Thanks for sharing, cheers

**Comment by andifalk** [comment]
Hi @jpasantos, 
I am working on this. 
Just committed new code to update to version 1.0.0 of the spring authorization server and spring boot 3.0.0.
What's missing is re-adding customization of user info and JWT access/id tokens (this has changed pretty much).

**Comment by andifalk** [comment]
Hi @jpasantos,
please check the current implementation. Fully updated to spring authorization server 1.0.0 and spring boot 3.0.0 including customizing user info.

**Comment by jpasantos** [comment]
Thanks @andifalk, I'm going to try it out. Cheers
