### ISSUE TITLE
Further customization for spring cloud gateway...

### ISSUE THREAD

**Issue by ENate** [andifalk/custom-spring-authorization-server#2]
Thanks for the custom example of spring-authorization-server. Can you comment whether it will be good to use this example (with further customization like storing users in a databse - in place of embedded data base, etc) to include a spring cloud gateway especially in a situation where one intends to apply it to authenticating/authorizing users in a microservice setting? 
 It seems introducing a gateway as a resource server/client is a hassle. But this is not clear to me - because you customized this example differently.

**Comment by ENate** [comment]
But thanks for the custom example. I was wondering if I can use this for an application containing several services. It seems introducing a gateway as a resource server/client is a hassle. But this exception is not clear to me.

**Comment by ENate** [comment]
Still got the following ``` Did not protect against CSRF since request did not match And [CsrfNotRequired [TRACE, HEAD, GET, OPTIONS], Not [Or [org.springframework.security.oauth2.server.authorization.config.annotation.web.configurers.OAuth2AuthorizationServerConfigurer$$Lambda$811/0x00000001005c66e0@3d7721a5, org.springframework.security.config.annotation.web.configurers.oauth2.server.resource.OAuth2ResourceServerConfigurer$BearerTokenRequestMatcher@e59ca2c]]] ```

**Comment by andifalk** [comment]
Hi @ENate 
to replace the H2 database you may follow the corresponding how-to documentation for using JPA as a persistence base for the authorization server, see here for details:
https://docs.spring.io/spring-authorization-server/docs/current/reference/html/guides/how-to-jpa.html 
This project is not intended to be used as a base for the spring cloud gateway. Usually, you should use separate applications for the authorization server and the gateway.
