### ISSUE TITLE
API to generate JWT token for a client

### ISSUE THREAD

**Issue by deeptiantony** [andifalk/custom-spring-authorization-server#3]
Hi, 

I started the application and was able to call GET http://localhost:9000/.well-known/openid-configuration, to view the configs available. 

But when I am trying to generate JWT token for a particular client, say demo-client, I'm facing issues like 401 Unauthorized or invalid_client. @andifalk  Could you please help with exactly what all we need to pass in the API call -- http://localhost:9000/oauth2/token?grant_type=client_credentials.

Appreciate any help.

**Comment by andifalk** [comment]
@deeptiantony thanks for submitting this issue, please re-test with lastest code :-)
